"""empty message

Revision ID: 566b8304dc53
Revises: e7617035d6bc
Create Date: 2017-08-15 11:48:37.107562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566b8304dc53'
down_revision = 'e7617035d6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify', sa.Column('description', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'spotify', ['description'])
    op.add_column('video', sa.Column('description', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'video', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_column('video', 'description')
    op.drop_constraint(None, 'spotify', type_='unique')
    op.drop_column('spotify', 'description')
    # ### end Alembic commands ###
