"""empty message

Revision ID: c3d9f870710e
Revises: fc8e6f6af1ed
Create Date: 2017-08-18 18:38:37.180472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9f870710e'
down_revision = 'fc8e6f6af1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
