"""empty message

Revision ID: fc8e6f6af1ed
Revises: 566b8304dc53
Create Date: 2017-08-15 15:48:07.913514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8e6f6af1ed'
down_revision = '566b8304dc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_text_text_key', 'app_text', type_='unique')
    op.drop_constraint('event_location_key', 'event', type_='unique')
    op.drop_constraint('event_name_key', 'event', type_='unique')
    op.drop_constraint('news_article_content_key', 'news_article', type_='unique')
    op.drop_constraint('spotify_embedded_link_key', 'spotify', type_='unique')
    op.drop_constraint('video_embedded_link_key', 'video', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('video_embedded_link_key', 'video', ['embedded_link'])
    op.create_unique_constraint('spotify_embedded_link_key', 'spotify', ['embedded_link'])
    op.create_unique_constraint('news_article_content_key', 'news_article', ['content'])
    op.create_unique_constraint('event_name_key', 'event', ['name'])
    op.create_unique_constraint('event_location_key', 'event', ['location'])
    op.create_unique_constraint('app_text_text_key', 'app_text', ['text'])
    # ### end Alembic commands ###
